### ISSUE TITLE
[Warning]: You are using outdated keywords.  

### ISSUE THREAD

**Issue by TakuNishiumi** [MNGuenther/allesfitter#16]
I got this warning.
What should I do?

```
Estimating errors and baselines... this will take a couple of minutes. Please be patient, you will get notified once everything is completed.



allesfitter version
--------------------------

v1.1.1

Shifting epochs into the data center:
--------------------------

Companion b
	input epoch: 2458931.25

###############################################################################
M1 flux
###############################################################################

Starting...
You are using outdated keywords. Automatically renaming log_err_flux_M1 ---> ln_err_flux_M1. Please fix this before the Duolingo owl comes to get you.
elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  0%|          | 3/1000 [00:00<00:42, 23.51it/s]
```

**Comment by MNGuenther** [comment]
Hi @TakuNishiumi two ways:you can just ignore it; such warnings are non-crucial and just encourage you to rename the variables to stay up-to-date with new allesfitter versions

**Comment by TakuNishiumi** [comment]
Hi, @MNGuenther, Thank you.
 
I just set it by GUI.
By the way, When I run "7. run the fit", I got this error.
I worries about this relates to the parameter name.

```
allesfitter version
--------------------------

v1.1.1

Shifting epochs into the data center:
--------------------------

Companion b
	input epoch: 2458931.25

Running MCMC...
--------------------------

Running full MCMC
emcee: Exception while calling your likelihood function:
  params: [ 7.07000141e-02  2.08544134e-01  2.45893125e+06  5.00000001e-01
  5.00000006e-01 -6.88999999e+00  1.00000011e-01  5.99999977e-01]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "/home/taku/anaconda3/envs/py37/lib/python3.7/site-packages/emcee/ensemble.py", line 545, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/home/taku/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py", line 101, in mcmc_lnprob
    ln = mcmc_lnlike(theta)
  File "/home/taku/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py", line 46, in mcmc_lnlike
    lnlike = calculate_lnlike_total(params)
  File "/home/taku/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/computer.py", line 1138, in calculate_lnlike_total
    gp = baseline_get_gp(params, inst, key)
  File "/home/taku/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/computer.py", line 1542, in baseline_get_gp
    kernel = terms.Matern32Term(log_sigma=params['baseline_gp_matern32_lnsigma_'+key+'_'+inst],
KeyError: 'baseline_gp_matern32_lnsigma_flux_M1'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-111-5f545b055bd0> in run_mcmc_fit(change)
     26     def run_mcmc_fit(change):
     27         button_run_mcmc_fit.style.button_color = 'lightgreen'
---> 28         allesfitter.mcmc_fit(INPUT['datadir'])
     29         allesfitter.mcmc_output(INPUT['datadir'])
     30 

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py in mcmc_fit(datadir)
    211                                         mcmc_lnprob,
    212                                         backend=backend)
--> 213         sampler = run_mcmc(sampler)
    214         t1 = timer()
    215         timemcmc = (t1-t0)

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py in run_mcmc(sampler)
    183                          (config.BASEMENT.settings['mcmc_total_steps'] - already_completed_steps)/config.BASEMENT.settings['mcmc_thin_by'],
    184                          thin_by=config.BASEMENT.settings['mcmc_thin_by'],
--> 185                          progress=config.BASEMENT.settings['print_progress'])
    186 
    187         return sampler

~/anaconda3/envs/py37/lib/python3.7/site-packages/emcee/ensemble.py in run_mcmc(self, initial_state, nsteps, **kwargs)
    382 
    383         results = None
--> 384         for results in self.sample(initial_state, iterations=nsteps, **kwargs):
    385             pass
    386 

~/anaconda3/envs/py37/lib/python3.7/site-packages/emcee/ensemble.py in sample(self, initial_state, log_prob0, rstate0, blobs0, iterations, tune, skip_initial_state_check, thin_by, thin, store, progress)
    283             state.blobs = blobs0
    284         if state.log_prob is None:
--> 285             state.log_prob, state.blobs = self.compute_log_prob(state.coords)
    286         if np.shape(state.log_prob) != (self.nwalkers,):
    287             raise ValueError("incompatible input dimensions")

~/anaconda3/envs/py37/lib/python3.7/site-packages/emcee/ensemble.py in compute_log_prob(self, coords)
    425                 map_func = map
    426             results = list(
--> 427                 map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
    428             )
    429 

~/anaconda3/envs/py37/lib/python3.7/site-packages/emcee/ensemble.py in __call__(self, x)
    543     def __call__(self, x):
    544         try:
--> 545             return self.f(x, *self.args, **self.kwargs)
    546         except:  # pragma: no cover
    547             import traceback

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py in mcmc_lnprob(theta)
     99     else:
    100 #        try:
--> 101         ln = mcmc_lnlike(theta)
    102         return lp + ln
    103 #        except:

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/mcmc.py in mcmc_lnlike(theta)
     44 
     45     params = update_params(theta)
---> 46     lnlike = calculate_lnlike_total(params)
     47 
     48 #    lnlike = 0

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/computer.py in calculate_lnlike_total(params)
   1136                     x = config.BASEMENT.data[inst]['time'] #pointer!
   1137                     y = config.BASEMENT.data[inst][key] - model - stellar_var
-> 1138                     gp = baseline_get_gp(params, inst, key)
   1139                     try:
   1140                         gp.compute(x, yerr=yerr_w)

~/anaconda3/envs/py37/lib/python3.7/site-packages/allesfitter/computer.py in baseline_get_gp(params, inst, key)
   1540 
   1541     elif config.BASEMENT.settings['baseline_'+key+'_'+inst] == 'sample_GP_Matern32':
-> 1542         kernel = terms.Matern32Term(log_sigma=params['baseline_gp_matern32_lnsigma_'+key+'_'+inst], 
   1543                                     log_rho=params['baseline_gp_matern32_lnrho_'+key+'_'+inst])
   1544 

KeyError: 'baseline_gp_matern32_lnsigma_flux_M1'

```

**Comment by TakuNishiumi** [comment]
I updated to ver 1.1.2, but the problem still remains.
Do you have solutions?

**Comment by mwcraig** [comment]
> Did you set the params.csv file up with the GUI or by yourself (e.g. using a Text Editor)?

FYI, with version 1.2.4 I also get this warning when using the setting/param files from https://github.com/MNGuenther/allesfitter/tree/master/tutorials
