### ISSUE TITLE
Error when running the estimate_noise_out_of_transit function

### ISSUE THREAD

**Issue by franpoz** [MNGuenther/allesfitter#66]
Hi, 

I have a set of TESS data, and I want to use the `estimate_noise_out_of_transit` function. Unfortunately, I have this error: 

```
Running pre-run loop 1 / 1
Traceback (most recent call last):
  File "run_noise.py", line 4, in <module>
    allesfitter.estimate_noise_out_of_transit('TOI5530_noise')
  File "/home/student/allesenv/lib64/python3.8/site-packages/allesfitter/priors/estimate_noise.py", line 176, in estimate_noise_out_of_transit
    gp_decor(
  File "/home/student/allesenv/lib64/python3.8/site-packages/allesfitter/exoworlds_rdx/lightcurves/gp_decor.py", line 477, in gp_decor
    run_mcmc(sampler)
  File "/home/student/allesenv/lib64/python3.8/site-packages/allesfitter/exoworlds_rdx/lightcurves/gp_decor.py", line 457, in run_mcmc
    sampler.run_mcmc(p0, pre_run_steps, progress=True)
  File "/home/student/allesenv/lib64/python3.8/site-packages/emcee/ensemble.py", line 443, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/student/allesenv/lib64/python3.8/site-packages/emcee/ensemble.py", line 312, in sample
    raise ValueError(
ValueError: Initial state has a large condition number. Make sure that your walkers are linearly independent for the best performance

```
Any suggestion to solve this? 

Note: Allesfitter version 1.2.10

thanks a lot!

**Comment by MNGuenther** [comment]
Hi @franpoz, can you send me the allesfit folder (with all files and data) via email so I can try to diagnose it? My best guess would be it is some issue with how the initial guess is set or a typo in the params.csv file. I will try to have a look next week!

**Comment by szunigaf** [comment]
Hi Max, 
I have different error but in the same function, allesfitter is installed in a clean environment dedicated to run allesfitter (version 1.2.10). Do you have any idea wht would be the cause?

```  [/usr/local/lib/python3.10/dist-packages/emcee/ensemble.py](https://localhost:8080/#) in sample(self, initial_state, log_prob0, rstate0, blobs0, iterations, tune, skip_initial_state_check, thin_by, thin, store, progress, progress_kwargs)
    394         with get_progress_bar(progress, total, **progress_kwargs) as pbar:
    395             i = 0
--> 396             print(iterations)
    397             for _ in count() if iterations is None else range(int(iterations)):
    398                 for _ in range(yield_step):

TypeError: 'float' object cannot be interpreted as an integer 
```
